platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'WorkingTracker' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
end
